mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from story9.views import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('story9.urls')),
    path('',include('django.contrib.auth.urls')),
]

story9/urls.py
from django.urls import include, path
from . import views
from django.shortcuts import render
from django.conf.urls import url

app_name = 'story9'
urlpatterns = [
	path('',views.main,name='main'),
	path('landing/',views.landing,name='landing'),
]

story9/models.py
from django.db import models

# Create your models here.

story9/views.py
from django.shortcuts import render, redirect
import requests

def main(request):
	return render(request,'main.html')

def landing(request):
	return render(request,'registration/landing.html')

story9/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <title>{% block title %}Story 9{% endblock %}</title>
</head>
<body>
  {% include "navbar.html" %}
  <br>
  <main>
    <div class="container" align="center">
      {% block content %}
      {% endblock %}
    </div>
  </main>
</body>
</html>

story9/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home{% endblock %}

{% block content %}
	<br><br><br>
	<h1 style="font-family: Stencil Std, fantasy">Hey, you. Login first!</h1><br>
	<img style="width: 60%" src="{% static 'img/main1.jpg' %}"><br><br>
{% endblock %}

story9/templates/navbar.html
{% if user.is_authenticated %}
<nav class="navbar navbar-expand navbar-dark bg-dark d-flex justify-content-end fixed-top">
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav d-flex mr-auto">
      <a class="nav-item nav-link active" href="{% url 'story9:main' %}">Home<span class="sr-only">(current)</span></a>
    </div>
    <ul class="navbar-nav ml-auto">
        <a class="nav-item nav-link active" href="{% url 'logout' %}">Logout</a>
    </ul>
  </div>
</nav>

{% else %}

<nav class="navbar navbar-expand navbar-dark bg-dark d-flex justify-content-end fixed-top">
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav d-flex mr-auto">
      <a class="nav-item nav-link active" href="{% url 'story9:main' %}">Home <span class="sr-only">(current)</span></a>
    </div>
    <ul class="navbar-nav ml-auto">
        <a class="nav-item nav-link active" href="{% url 'login' %}">Login</a>
      </ul>
  </div>
</nav>
{% endif %}